version: '3'

networks:
  common_networks:

services:
  graphql-vanilla:
    build:
      context: .
      dockerfile: Dockerfile
      ports:
        - 4000:4000
      networks:
        - common_networks

volumes:
  pgdata: